# Address vim mode switching delay
set -s escape-time 0

# Increase scrollback buffer size
set -g history-limit 50000

# Tmux messages are displayed for 4 seconds
set -g display-time 4000

# Refresh 'status-left' and 'status-right' more often
set -g status-interval 5

# Upgrade $TERM
set -g default-terminal "screen-256color"

# Emacs key bindings in tmux command prompt
set -g status-keys emacs

# Focus events enabled for terminals that support them
set -g focus-events on

# Super useful when using "grouped sessions" and multi-monitor setup
setw -g aggressive-resize on

# Change prefix keybind
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Easier and faster switching between next/prev window
bind C-p previous-window
bind C-n next-window

# Enable mouse mode
# set -g mouse on

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-yank'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run -b '~/.tmux/plugins/tpm/tpm'
